import type { GenerationTask } from "./types";

const now = Date.now();

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "task-001",
    type: "image",
    model: "Midjourney v6",
    prompt: "Футуристичный интерьер студии в тёплой тёмной палитре ERA2",
    status: "running",
    progress: 64,
    createdAt: now - 1000 * 60 * 24,
    updatedAt: now - 1000 * 12,
    credits: 12,
    etaSeconds: 48,
  },
  {
    id: "task-002",
    type: "text",
    model: "GPT-4o",
    prompt: "Подготовь короткий сценарий для презентации нового AI-продукта",
    status: "running",
    progress: 37,
    createdAt: now - 1000 * 60 * 21,
    updatedAt: now - 1000 * 8,
    credits: 4,
    etaSeconds: 24,
  },
  {
    id: "task-003",
    type: "video",
    model: "Runway Gen-3",
    prompt: "Анимированный ролик: камера пролетает над неоновым городом ночью",
    status: "queued",
    progress: 0,
    createdAt: now - 1000 * 60 * 18,
    updatedAt: now - 1000 * 60 * 18,
    credits: 28,
    etaSeconds: 180,
  },
  {
    id: "task-004",
    type: "audio",
    model: "elevenLabs",
    prompt: "Озвучка спокойным мужским голосом для onboarding-видео",
    status: "queued",
    progress: 0,
    createdAt: now - 1000 * 60 * 15,
    updatedAt: now - 1000 * 60 * 15,
    credits: 8,
    etaSeconds: 75,
  },
  {
    id: "task-005",
    type: "text",
    model: "Claude Sonnet",
    prompt: "Сформулируй 5 вариантов заголовка для лендинга AI-агрегатора",
    status: "queued",
    progress: 0,
    createdAt: now - 1000 * 60 * 11,
    updatedAt: now - 1000 * 60 * 11,
    credits: 5,
    etaSeconds: 35,
  },
  {
    id: "task-006",
    type: "image",
    model: "DALL-E 3",
    prompt: "Минималистичная обложка для статьи про генеративные модели",
    status: "done",
    progress: 100,
    createdAt: now - 1000 * 60 * 48,
    updatedAt: now - 1000 * 60 * 42,
    credits: 10,
    etaSeconds: 0,
    resultUrl: "/mock/results/task-006.png",
  },
  {
    id: "task-007",
    type: "audio",
    model: "Suno",
    prompt: "Короткий энергичный джингл для product demo",
    status: "done",
    progress: 100,
    createdAt: now - 1000 * 60 * 38,
    updatedAt: now - 1000 * 60 * 30,
    credits: 16,
    etaSeconds: 0,
    resultUrl: "/mock/results/task-007.mp3",
  },
  {
    id: "task-008",
    type: "video",
    model: "Runway Gen-3",
    prompt: "Вертикальное видео с плавным появлением интерфейса на тёмном фоне",
    status: "failed",
    progress: 52,
    createdAt: now - 1000 * 60 * 34,
    updatedAt: now - 1000 * 60 * 29,
    credits: 24,
    etaSeconds: 0,
    error: "Модель временно недоступна",
  },
  {
    id: "task-009",
    type: "text",
    model: "GPT-4o",
    prompt: "Собери список тезисов для письма инвесторам",
    status: "cancelled",
    progress: 18,
    createdAt: now - 1000 * 60 * 27,
    updatedAt: now - 1000 * 60 * 23,
    credits: 3,
    etaSeconds: 0,
  },
];

export const cloneFreshSeed = () => {
  const freshNow = Date.now();
  const offset = freshNow - now;

  return generationTaskSeed.map<GenerationTask>((task) => ({
    ...task,
    createdAt: task.createdAt + offset,
    updatedAt: task.updatedAt + offset,
  }));
};
